"""create saferoute database

Revision ID: 7e35e5c35590
Revises: 
Create Date: 2026-09-28 16:05:31.443786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7e35e5c35590'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'data_sources',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'model_versions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('model_name', sa.String(length=150), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('algorithm', sa.String(length=150), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=True),
        sa.Column('model_path', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'risk_zones',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('risk_level', sa.String(length=30), nullable=False),
        sa.Column('risk_score', sa.Float(), nullable=False),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geometry(
                geometry_type='POLYGON',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_risk_zones_geometry',
        'risk_zones',
        ['geometry'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_users_email'),
        'users',
        ['email'],
        unique=True
    )

    op.create_table(
        'risk_observations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('source_id', sa.UUID(), nullable=True),
        sa.Column('risk_type', sa.String(length=100), nullable=False),
        sa.Column('risk_level', sa.String(length=30), nullable=False),
        sa.Column('risk_score', sa.Float(), nullable=True),
        sa.Column(
            'location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'observed_at',
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['data_sources.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_risk_observations_location',
        'risk_observations',
        ['location'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'routes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column(
            'start_location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'destination_location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geometry(
                geometry_type='LINESTRING',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry'
            ),
            nullable=True
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_routes_destination_location',
        'routes',
        ['destination_location'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_index(
        'idx_routes_geometry',
        'routes',
        ['geometry'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_index(
        'idx_routes_start_location',
        'routes',
        ['start_location'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'weather_observations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('source_id', sa.UUID(), nullable=True),
        sa.Column(
            'location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True),
        sa.Column('rainfall', sa.Float(), nullable=True),
        sa.Column('wind_speed', sa.Float(), nullable=True),
        sa.Column('visibility', sa.Float(), nullable=True),
        sa.Column(
            'weather_condition',
            sa.String(length=100),
            nullable=True
        ),
        sa.Column(
            'observed_at',
            sa.DateTime(timezone=True),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['source_id'],
            ['data_sources.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_weather_observations_location',
        'weather_observations',
        ['location'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'alerts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('route_id', sa.UUID(), nullable=True),
        sa.Column('alert_type', sa.String(length=100), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('severity', sa.String(length=30), nullable=False),
        sa.Column(
            'location',
            geoalchemy2.types.Geometry(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry'
            ),
            nullable=True
        ),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['route_id'],
            ['routes.id']
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_alerts_location',
        'alerts',
        ['location'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'route_segments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('route_id', sa.UUID(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column(
            'geometry',
            geoalchemy2.types.Geometry(
                geometry_type='LINESTRING',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False
            ),
            nullable=False
        ),
        sa.Column(
            'distance_meters',
            sa.Float(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['route_id'],
            ['routes.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'idx_route_segments_geometry',
        'route_segments',
        ['geometry'],
        unique=False,
        postgresql_using='gist'
    )

    op.create_table(
        'risk_predictions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'route_segment_id',
            sa.UUID(),
            nullable=False
        ),
        sa.Column(
            'model_version_id',
            sa.UUID(),
            nullable=False
        ),
        sa.Column(
            'risk_score',
            sa.Float(),
            nullable=False
        ),
        sa.Column(
            'risk_level',
            sa.String(length=30),
            nullable=False
        ),
        sa.Column(
            'predicted_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['model_version_id'],
            ['model_versions.id']
        ),
        sa.ForeignKeyConstraint(
            ['route_segment_id'],
            ['route_segments.id']
        ),
        sa.PrimaryKeyConstraint('id')
    )

    # spatial_ref_sys is managed by the PostGIS extension.
    # It should NOT be created or dropped by this migration.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('risk_predictions')

    op.drop_index(
        'idx_route_segments_geometry',
        table_name='route_segments',
        postgresql_using='gist'
    )
    op.drop_table('route_segments')

    op.drop_index(
        'idx_alerts_location',
        table_name='alerts',
        postgresql_using='gist'
    )
    op.drop_table('alerts')

    op.drop_index(
        'idx_weather_observations_location',
        table_name='weather_observations',
        postgresql_using='gist'
    )
    op.drop_table('weather_observations')

    op.drop_index(
        'idx_routes_start_location',
        table_name='routes',
        postgresql_using='gist'
    )
    op.drop_index(
        'idx_routes_geometry',
        table_name='routes',
        postgresql_using='gist'
    )
    op.drop_index(
        'idx_routes_destination_location',
        table_name='routes',
        postgresql_using='gist'
    )
    op.drop_table('routes')

    op.drop_index(
        'idx_risk_observations_location',
        table_name='risk_observations',
        postgresql_using='gist'
    )
    op.drop_table('risk_observations')

    op.drop_index(
        op.f('ix_users_email'),
        table_name='users'
    )
    op.drop_table('users')

    op.drop_index(
        'idx_risk_zones_geometry',
        table_name='risk_zones',
        postgresql_using='gist'
    )
    op.drop_table('risk_zones')

    op.drop_table('model_versions')
    op.drop_table('data_sources')

    # spatial_ref_sys is managed by the PostGIS extension.
    # It should NOT be recreated by this migration.

    # ### end Alembic commands ###