"""add authentication fields

Revision ID: bba7dac8910e
Revises: 7e35e5c35590
Create Date: 2026-10-05 19:16:40.177276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba7dac8910e'
down_revision: Union[str, Sequence[str], None] = '7e35e5c35590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')

    # ### end Alembic commands ###