'use client';
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Clock3, Compass, LayoutDashboard, Map, Settings, Menu, X, UserRound } from "lucide-react";
import { useState } from "react";
import { Logo } from "@/components/Logo";
import { cn } from "@/lib/utils";
const nav=[['/dashboard','Dashboard',LayoutDashboard],['/route','Plan Route',Compass],['/history','History',Clock3],['/alerts','Alerts',Bell],['/settings','Settings',Settings]] as const;
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);return <div className="min-h-screen bg-[#f7f9fc]"><aside className={cn('fixed inset-y-0 left-0 z-50 w-64 border-r border-slate-200 bg-white p-5 transition-transform lg:translate-x-0',open?'translate-x-0':'-translate-x-full')}><div className="flex items-center justify-between"><Logo/><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-9 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={cn('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium',path===href?'bg-[#eaf6f1] text-[#176b57]':'text-slate-600 hover:bg-slate-50')}><Icon size={18}/>{label}</Link>)}</div><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#dcefe8] text-[#176b57]"><UserRound size={18}/></div><div><p className="text-sm font-semibold">Soham</p><p className="text-xs text-slate-500">Personal account</p></div></div></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:px-8"><button className="rounded-lg p-2 hover:bg-slate-100 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="hidden items-center gap-2 text-sm text-slate-500 md:flex"><Map size={17} className="text-[#176b57]"/> Risk-aware urban navigation</div><div className="flex items-center gap-3"><button aria-label="Notifications" className="rounded-xl p-2 text-slate-500 hover:bg-slate-100"><Bell size={19}/></button><div className="hidden h-8 w-px bg-slate-200 sm:block"/><span className="hidden text-sm font-semibold sm:block">Mumbai</span></div></header><main className="min-h-[calc(100vh-4rem)] p-4 pb-24 md:p-6 lg:p-8 lg:pb-8">{children}</main></div><nav className="fixed bottom-0 left-0 right-0 z-40 grid grid-cols-4 border-t border-slate-200 bg-white/95 p-2 backdrop-blur lg:hidden">{nav.slice(0,4).map(([href,label,Icon])=><Link key={href} href={href} className={cn('flex flex-col items-center gap-1 rounded-xl py-2 text-[11px]',path===href?'text-[#176b57]':'text-slate-500')}><Icon size={18}/>{label==='Dashboard'?'Home':label==='Plan Route'?'Routes':label}</Link>)}</nav></div>}
